---
title: Ordinal numerals (Maps & Data)
author: Polina Nasledskova, Ivan Netkachev
date: 'Last update: December 2021'
bibliography: ./data/orig_bib/ordinals.bib
csl: ./data/apa.csl
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = '')
library(lingglosses)
```

See [the chapter text](09_ordinals.html)

```{r}
library(RefManageR)
BibOptions(check.entries = FALSE, style = 'text', bib.style = 'authoryear')
article_citation <- BibEntry(bibtype = 'Incollection', 
 key='nasledskova2021',
 title='Ordinal numerals',
 author='Polina Nasledskova and Ivan Netkachev',
 year='2021',
 editor= 'Daniel, Michael  and Filatov, Konstantin and Moroz, George and Mukhin, Timofey and Naccarato, Chiara and Verhees, Samira',
 publisher='Linguistic Convergence Laboratory, NRU HSE',
 address='Moscow',
 booktitle= 'Typological Atlas of the languages of Daghestan (TALD)',
 url='http://lingconlab.ru/dagatlas')
```

## {.tabset .tabset-fade .tabset-pills} 

### Plain text
```{r, results = 'asis'}
print(article_citation, .opts = list(style = 'text'))
```

### BibTeX

```{r}
print(article_citation, .opts = list(style = 'Bibtex'))
```

```{r, child='data/orig_rmd/ordinals_map.Rmd'}
```

## References

```{r, results='asis'}
PrintBibliography(bib)
```

