---
title: "Typological Atlas of the languages of Daghestan"
output:
  html_document:
    include:
      in_header: ./html/header_index.html
---

***

Languages of Daghestan have a long descriptive tradition. Available grammars contain a wealth of data which, however, have not been analyzed from an areal point of view. The goal of this project is to develop a tool for the visualization of information about linguistic structures characteristic of Daghestan. The atlas is based almost exclusively on data from published grammars, and can therefore be used for bibliographical research and as a source of references on parameters of interest. A key task of the project is the creation of maps and visualizations that allow us to combine metadata and genealogical parameters with information on a particular feature. This task presupposes the inventory and evaluation of available sources on grammatical information. Data from the Atlas can be used to formulate hypotheses about the area and scenarios for the distribution of certain phenomena. The Atlas will also allow a wider audience to become familiar with the linguistic diversity of Daghestan.

***
