---
title: "References"
output:
  html_document:
    include:
      in_header: ./html/header_references.html
---

***

# Grammars, dictionaries and other sources

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

library(tidyverse)
library(DT)
library(RefManageR)

idioms <- read_tsv("./data/biblib_idioms.tsv")
biblib <- read_tsv("./data/biblib.tsv")
dtable <- left_join(idioms, biblib, by=c("bibtexkey" = "BIBTEXKEY"))

bib <- ReadBib(file = "./data/bibliography.bib") # do not like more than 3 "," in a cyrillic row. why??!? UPD: use "and" instead of "и"

# dtable %>% 
#   mutate(refer = bib[BIBTEXKEY]) -> dtable  # do not work

```

```{r include=FALSE}
# add cite buttons, see https://www.cyberforum.ru/javascript-beginners/thread2570247.html about problems


# dtable %>% 
#   mutate(idiom = paste('<br>', 
#                      '<input type="text" value="', 
#                      language, 
#                      '" id="myInput">', 
#                      '<button onclick="myFunction()">Copy text</button>',
#                      sep = '')) -> dtable

dtable %>% 
  mutate(year = as.integer(year)) %>% 
  select(language, idiom, title, author, year, source_type) -> dtable

```

<!-- <!--html_preserve--> -->
<!-- <script> -->
<!-- function myFunction() { -->
<!--   /* Get the text field */ -->
<!--   var copyText = document.getElementById("myInput"); -->

<!--   /* Select the text field */ -->
<!--   copyText.select(); -->
<!--   copyText.setSelectionRange(0, 99999); /* For mobile devices */ -->

<!--    /* Copy the text inside the text field */ -->
<!--   navigator.clipboard.writeText(copyText.value); -->

<!--   /* Alert the copied text */ -->
<!--   alert("Copied the text: " + copyText.value); -->
<!-- } -->

<!-- </script> -->
<!-- <!--/html_preserve--> -->

```{r}
# generate searchable datatable
DT::datatable(dtable,
              filter = 'top', 
              escape = FALSE, 
              rownames = FALSE,
              options = list(
                pageLength = 10, 
                autoWidth = TRUE,
                dom = 'fltpi')
              )
```

***